### ISSUE TITLE
catch_and_close w/ Bad variant index

### ISSUE THREAD

**Issue by 633kh4ck** [EOSIO/history-tools#105]
**Environment**:
```bash
$ pwd
/eosio/eos
$ git branch
  master
* release/2.1.x
$ git rev-parse HEAD
203ff0ca0d780a3f62c3debcb59c90b2c3dc683d
$ cd ../history-tools && pwd
/eosio/history-tools
$ git branch
* (HEAD detached at upstream/fix/safe-deltas-unpack)
  master
$ git rev-parse HEAD
7c251e4ecb29d4de622b34ab779bb129d2d59586
```

**Related issue**: #103 (must be addressed first)

**Issue**:
`fill-pg` produces the same "**Bad variant index**" error regardless of the `nodeos` version used: 2.1.0-rc1 (built from tag pinned to EOSIO/eos@c7487e7) or 2.1.0 (built from _release/2.1.x_ branch at EOSIO/eos@203ff0c). Presumably it crashes immediately after receiving the first `get_blocks_result_v1` (right after the `write_stream` function is executed).

**Comment by cppfuns** [comment]
Many friends in the community are waiting for this issue to be fixed, and hope it will be resolved as soon as possible

**Comment by jgiszczak** [comment]
@633kh4ck Please try again with the current `develop` branch of `history-tools`.  We have been resolving compatibility issues there.

**Comment by 633kh4ck** [comment]
@jgiszczak This issue is not resolved and (to be clear) is locked by https://github.com/EOSIO/history-tools/issues/103#issuecomment-782344199

**Comment by 633kh4ck** [comment]
Closed due to the lack of support from the maintainers and time for further independent research.

**Comment by cppfuns** [comment]
> 由于维护者缺乏支持以及没有时间进行进一步的独立研究而关闭。

Worrying about the current technological development of EOS
