### ISSUE TITLE
bug in doc

### ISSUE THREAD

**Issue by salisbury-espinosa** [EOSIO/history-tools#12]
https://github.com/EOSIO/history-tools/blob/master/doc/build-ubuntu-1810.md#release-build
```
ninja
../build-test
```
but build-test is removed by https://github.com/EOSIO/history-tools/commit/f76216e5d1096e82b6716e2a84864bc19f98d7fa

**Comment by tbfleming** [comment]
Obsoleted by new documentation. Support switched from 18.10 to 18.04.
