### ISSUE TITLE
feature request: date_create field for all

### ISSUE THREAD

**Issue by salisbury-espinosa** [EOSIO/history-tools#13]
record insertion time for all tables

**Comment by tbfleming** [comment]
This information is available via `block_index` (master branch) or `block_num` (1.8 branch).

**Comment by salisbury-espinosa** [comment]
date_create of **block** !== date_create of **row in db**  
*block_num* === height of block (not timestamp)
@tbfleming

**Comment by tbfleming** [comment]
You can get the timestamp from the `block_info` table.

**Comment by salisbury-espinosa** [comment]
@tbfleming 
> You can get the timestamp from the block_info table.

https://github.com/EOSIO/history-tools/issues/13#issuecomment-500472318
> date_create of block !== date_create of row in db

`block production time` !== `timestamp of saving data to the database`
it would be nice to keep both parameters

**Comment by tbfleming** [comment]
What is the use case for that?

**Comment by tbfleming** [comment]
No response to use case question
