### ISSUE TITLE
how to get value from `act_data` in `action_trace` table for act_name='transfer'?

### ISSUE THREAD

**Issue by salisbury-espinosa** [EOSIO/history-tools#17]
I would like to receive detailed information on transfers for the account

**Comment by tbfleming** [comment]
You need to use an abi deserializer, such as abieos or eosjs

**Comment by salisbury-espinosa** [comment]
@tbfleming maybe it makes sense to save the result of this action immediately in storage (postgresql) when filling out the scheme?

**Comment by salisbury-espinosa** [comment]
@tbfleming 
> You need to use an abi deserializer, such as abieos or eosjs
hm, i just tried eosjs...

```js
const fromHexString = hexString => new Uint8Array(hexString.match(/.{1,2}/g).map(byte => parseInt(byte, 16)));
const { Api, JsonRpc, RpcError } = require('eosjs');
const fetch = require('node-fetch');
const { TextEncoder, TextDecoder } = require('util');  
const rpc = new JsonRpc('http://127.0.0.1:8888', { fetch });
const api = new Api({ rpc, textDecoder: new TextDecoder(), textEncoder: new TextEncoder()});
/**

   receiver   | act_account  | block_num |                          transaction_id                          | action_ordinal |                                                         act_data                                                         
--------------+--------------+-----------+------------------------------------------------------------------+----------------+--------------------------------------------------------------------------------------------------------------------------
 eosio.token  | eosio.token  |  17833498 | 5713A31DA5EFFDAB86AB618B800B88C0115DBD9DBF5C6CFA2274CCEF0C1EF5DE |              2 | \x3042a6875e7a90c310b2b9062173b239e80300000000000004454f530000000000
**/
api.rawAbiToJson(fromHexString('3042a6875e7a90c310b2b9062173b239e80300000000000004454f530000000000'));

```
```shell
node index.js 
/home/duo/sources/eosjs_test/node_modules/eosjs/dist/eosjs-serialize.js:133
            throw new Error('Read past end of buffer');
            ^

Error: Read past end of buffer
    at SerialBuffer.getUint8Array (/home/duo/sources/eosjs_test/node_modules/eosjs/dist/eosjs-serialize.js:133:19)
```

**Comment by tbfleming** [comment]
`rawAbiToJson` converts an abi, not action data

**Comment by salisbury-espinosa** [comment]
> converts an abi, not action data
so 
how to get value from `act_data` in `action_trace` table for act_name='transfer'?

**Comment by salisbury-espinosa** [comment]
@tbfleming if I understood everything correctly, it is necessary to retrieve this data before inserting it into the database using this method:

https://github.com/EOSIO/eos/blob/master/libraries/chain/include/eosio/chain/controller.hpp#L273

**Comment by tbfleming** [comment]
fill-pg leaves it in binary to save space and to save fill time. JSON conversion expands the size by large factor. Some applications work better with data in its binary format; e.g. wasm-ql. Applications which need the data in json, but only need a small subset (e.g. transfers) are better off not having the overhead of the remaining data converted to json.

If the database will only be used by apps which need a small subset of the data, then a custom-written filler that works in place of fill-pg will probably be a better match.
