### ISSUE TITLE
how to detect what was orphan?

### ISSUE THREAD

**Issue by salisbury-espinosa** [EOSIO/history-tools#22]
```sql
select irreversible from fill_status UNION ALL select max(block_num) from action_trace;
 irreversible 
--------------
     34480901
     34481230
(2 rows)
```
the tail (329 blocks) may be overwritten by other data due to orphan. 
How to understand that this action belongs to orphan?
Perhaps you need to add an id_block not only to the block_info table?

**Comment by tbfleming** [comment]
Use queries like this to see only irreversible:

```sql
select * from chain.action_trace where block_num <= (select irreversible from chain.fill_status);
```
