### ISSUE TITLE
feature request: Add filtering capability

### ISSUE THREAD

**Issue by raphaelgodro** [EOSIO/history-tools#23]
With the now deprecated mongo db plugin, one really appreciated feature was to be able to filter out some actions. It is currently impossible to do it without a custom middleware, we should be able to put action filters in the config.

**Comment by gituser** [comment]
I agree on this, there should be similar mechanism for filtering as in original history plugin or some sort of. To be able to filter transactions on certain token, receiver and sender.

**Comment by alexander-a-semin** [comment]
Add filtering capability is the most important feature for out team. Please, do it ASAP.

**Comment by tbfleming** [comment]
Let's expand on this a bit. What kinds of things should it support filtering on?

**Comment by alexander-a-semin** [comment]
Same as history plugin, but at least code and receiver account name.

**Comment by gituser** [comment]
@tbfleming adding similar `filter-on` as in deprecated history plugin should be a good start!

**Comment by alexander-a-semin** [comment]
@tbfleming is there any forecast for the implementation of the feature?

**Comment by tbfleming** [comment]
I'm working on this now. Here's a snippet describing it which will go into the documentation:

## Transaction filters

`--filt-trx` creates a set of transaction filtering rules. It has the following syntax:

```
--filt-trx include:status:receiver:act_account:act_name
```

It ignores whitespace within the pattern.

| Field         | May be empty? | Description |
| ------------- | ------------- | ----------- |
| include       | No            | "`+`" to pass a matching action, or "`-`" to not pass |
| status        | Yes           | Transaction status. May be one of: `executed`, `soft_fail`, `hard_fail`, `delayed`, `expired` |
| receiver      | Yes           | The account which originally received the action, or the account which received a copy (`require_recipient`). |
| act_account   | Yes           | The account which received the original. This is called `code` or `first_receiver` in the CDT. |
| act_name      | Yes           | The name of the action |

`--filt-trx` may be specified multiple times. This creates a list of rules. The filter checks an action against each rule in order. As soon as it finds a rule which matches the action it stops. The action passes if `include` is `+`. The action doesn't pass if `include` is `-`. If no rules match, then the action doesn't pass.

The filler writes a transaction to the database if any of the transaction's actions pass the filter. When this happens, it writes all actions in the transaction, including ones that didn't pass.

### Transaction filter examples

* Include all transactions. Includes deferred transactions which haven't executed
  yet or have failed. This is the default if no `--filt-trx` is provided:

```
--filt-trx "+:        :            :            :"
```

* Include all executed transactions. Excludes deferred transactions which haven't executed
  yet or have failed:

```
--filt-trx "+:executed:            :            :"
```

* Include all executed transactions, but exclude some spam:

```
--filt-trx "-:        :blocktwitter:blocktwitter:"
--filt-trx "+:executed:            :            :"
```

* Include all executed transfers. Includes all token contracts.

```
--filt-trx "+:executed:            :            :transfer"
```

* Include all executed transfers. Includes only `eosio.token`.

```
--filt-trx "+:executed:            :eosio.token :transfer"
```

* Include all executed transfers which notify specific accounts. Includes all token contracts.

```
--filt-trx "+:executed:myaccount1  :            :transfer"
--filt-trx "+:executed:myaccount2  :            :transfer"
```

* Include all executed transfers which notify specific accounts. Only includes `eosio.token`.

```
--filt-trx "+:executed:myaccount1  :eosio.token :transfer"
--filt-trx "+:executed:myaccount2  :eosio.token :transfer"
```

**Comment by tbfleming** [comment]
It's now in the develop branch

**Comment by alexander-a-semin** [comment]
@tbfleming Thanks a lot !
