### ISSUE TITLE
Need help migrating postgres db created with nodeos 1.7.4 to 1.8 branch

### ISSUE THREAD

**Issue by jingzhehu** [EOSIO/history-tools#34]
@tbfleming I recently upgraded to `nodeos 1.8.1` from `1.7.4`. Then `fill-pg (Alpha 0.1.0)` starts to complain with the error:

```
error 2019-07-29T14:57:49.295 thread-0  fill_pg_plugin.cpp:967        catch_and_close      ] 
ERROR:  column "block_num" does not exist
LINE 1: select block_num, block_id from "chain".received_block where...
               ^
HINT:  Perhaps you meant to reference the column "received_block.block_id".
```

Is there a way to make `fill-pg` work with existing schema from nodeos 1.7 branch without starting from scratch again (dropping the current database and recreate) ? 

Really appreciate your help and thanks in advance !

**Comment by tbfleming** [comment]
Right now there isn't a way to migrate. When history-tools reaches 1.0.0, then I expect that future versions will be able to migrate from 1.0.0.

**Comment by jingzhehu** [comment]
Got it. Thanks for the info !
