### ISSUE TITLE
Got error: expected table_delta_v0 got 380572

### ISSUE THREAD

**Issue by lucca65** [EOSIO/history-tools#44]
Hey I'm having this error:

<img width="1244" alt="Screen Shot 2019-08-06 at 16 28 14" src="https://user-images.githubusercontent.com/1082127/62571208-31e8e680-b867-11e9-82e6-54f385f5fa14.png">

Database has the schema created properly, but has only one block synced.

<img width="1110" alt="Screen Shot 2019-08-06 at 16 28 41" src="https://user-images.githubusercontent.com/1082127/62571239-4200c600-b867-11e9-8639-4c481c3c440d.png">

My EOS node is running `v1.7.4` and shows the following log:

```
info  2019-08-06T19:37:48.611 thread-0  state_history_plugin.c:119    start                ] incoming connection
error 2019-08-06T19:37:48.648 thread-0  state_history_plugin.c:278    on_fail              ] async_read: End of file
error 2019-08-06T19:37:48.649 thread-0  state_history_plugin.c:278    on_fail              ] async_write: Operation canceled
```

Does someone knows why this happens or something that might point me in the right direction?

Thanks a lot!

**Comment by tbfleming** [comment]
History tools needs nodeos `v.1.8.1`. 1.7 is incompatible.

**Comment by lucca65** [comment]
I see, I'll upgrade it then, thanks!

**Comment by tbfleming** [comment]
After you upgrade nodeos, use fill-pg's `--fpg-drop` to remove the corrupt schema.
