### ISSUE TITLE
Trying to build the history tool always throw error on ninja step 367

### ISSUE THREAD

**Issue by bakasura980** [EOSIO/history-tools#61]
I am using the provided Docker file for ubuntu 18.04 and when I try to build the image, everything goes just fine and on the last step (ninja) I reach 
[367/678] Building CXX object CMakeFiles/history-tools.dir/src/wasm_ql_plugin.cpp.o
and this always throw 
```
clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
```

**Comment by tbfleming** [comment]
Linux's out-of-memory killer probably killed it. If you're running Docker Desktop, then increase its RAM limit.

**Comment by bakasura980** [comment]
I will try it out. What about j10 option, what does it means ?

**Comment by tbfleming** [comment]
Build using 10 parallel processes. Make sure you assign at least 10 CPUs to Docker Desktop.

**Comment by bakasura980** [comment]
I have a VM with 12CPUs and 12 GB of RAM and the ninja build reaches step 375 and stays there for hours and nothing happens. Is this a normal?

**Comment by bakasura980** [comment]
How actually to run this toolset

**Comment by tbfleming** [comment]
It's not normal for it to pause more than a couple minutes. It probably needs more RAM.

See the documentation for how to use it after it's built. The documentation doesn't cover docker containers.

**Comment by bakasura980** [comment]
I finally succeed to compile all the things and I have fill-pg plugin enabled. 
I am trying to get a result from the chain as I have a running wasm-ql-pg. I have started it just like `./wasm-ql-pg` and when I try to execute this request:
`curl localhost:8880/v1/chain/get_abi -d '{"account_name": "eosio.token"}'`
I am getting `query failed: wasm linked function failure`. What does it mean

**Comment by tbfleming** [comment]
I just did a fresh build of the container; it didn't reproduce this issue.

Which branch are you on? What changes did you make to the dockerfile?

This change is now necessary since 1.8.1 was dropped:

from:
```
run wget https://github.com/EOSIO/eos/releases/download/v1.8.1/eosio_1.8.1-1-ubuntu-18.04_amd64.deb
run apt-get install -y ./eosio_1.8.1-1-ubuntu-18.04_amd64.deb
```

to:
```
run wget https://github.com/EOSIO/eos/releases/download/v1.8.6/eosio_1.8.6-1-ubuntu-18.04_amd64.deb
run apt-get install -y ./eosio_1.8.6-1-ubuntu-18.04_amd64.deb
```

**Comment by tbfleming** [comment]
`master` branch now has the above change. Tag `v0.2.1-alpha`

**Comment by bakasura980** [comment]
Actually I am not using Docker. I am using this https://eosio.github.io/history-tools/build-ubuntu-1804.html in order to build it. I processed it step by step and yes - I changed to v1.8.6. This is the only change. I am on the master branch. Could you specify what hardware you are using please

**Comment by bakasura980** [comment]
Also, is there a way to build only the fill-pg and wasm-ql ?

**Comment by bakasura980** [comment]
What will happen in the following scenario:
If we have two nodes and each of them stores in a different postgresql. If the first node goes down for some time after reconnection and syncing, does it lose the data processed in this gap time? If so, Is there a mechanism to sync it's db with the one from the second node. If for some reason the db vm goes down, is there a way to restore all of it's transactions data from the chain ?
