### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by huazhouwang** [EOSIO/history-tools#86]
Any one tell me is there any command i can ran? I only want to use it to trace inline action and get full history from api, but i find nothing about it from document.

**Comment by JoYeonJeong** [comment]
me too.
I REALLY want to know this..
Any one help me :(

**Comment by iamveritas** [comment]
@huazhouwang @JoYeonJeong 
hi there, did you have a chance to see this docs?
https://developers.eos.io/welcome/latest/tools/history-tools/index

**Comment by cppfuns** [comment]
> @huazhouwang @JoYeonJeong
> hi there, did you have a chance to see these docs?
> https://developers.eos.io/welcome/latest/tools/history-tools/index

I have read this document, but I don’t understand how to use it

**Comment by airstring** [comment]
> Any one tell me is there any command i can ran? I only want to use it to trace inline action and get full history from api, but i find nothing about it from document.

How did you solve it?
